% makefigure2_paper(savefigs)

%makes figures for Figure2 and S2 and demo the basic software

%% define constants and data locations

actatlasmainloc='./datalocs/MBLHmain.xlsx';
actatlassingleloc='./datalocs/MBsingle.xlsx';
actatlassingleloclh='./datalocs/LHsingle.xlsx';
tntatlasloc='./datalocs/TNTatlas.xlsx';

trajectoryloc='./datalocs/Figure2exampletraj.xlsx';
drivers={'lh1396','MB052B','MB077B','MB112C','MB434B','MB082C'};

%% plot example trajectories for LH and MB lines in Fig 2.
%generate example trajectory  (A B C D) -LEFT

trajectories_paper(actatlasmainloc,trajectoryloc,' ');

%% plot timecourses for these as well (same axis and axis labels) for Fig S2
%generate timecourses for LH/MB lines (A-D)

matchedtimecourses_paper(actatlasmainloc,drivers,'activation',' '); 


%% Make fly-by-fly plots for various LH/MB lines (Fig 2 A-D RIGHT)

load('./CleanBehaviourdata/extractedparameters/MBLHparameters/MainMBLHparameters.mat');
%this was generated by the following command: parameters=extract(actatlasmainloc,'resblankalwayson10s');

[siglinesup,siglinesdown,magnitudes,pvals]=plotparameters_FSB(actatlasmainloc,parameters,{'upwind','curvature','curvatureoff'},{'LHMB'},' ','region');

clear parameters;
%% Make fly-by-fly plots for additional LH and MB lines (Fig S2B)

load('./CleanBehaviourdata/extractedparameters/MBLHparameters/SuppMBparameters.mat');

[siglinesupmb,siglinesdownmb,magnitudesmb,pvalsmb]=plotparameters_FSB(actatlassingleloc,parameters,{'upwind','curvature','curvatureoff'},{'MBON'},' ','region');
clear parameters;

load('./CleanBehaviourdata/extractedparameters/MBLHparameters/SuppLHparameters.mat');
[siglinesuplh,siglinesdownlh,magnitudeslh,pvalslh]=plotparameters_FSB(actatlassingleloclh,parameters,{'upwind','curvature','curvatureoff'},{'LHMB'},' ','region');
clear parameters;


%% make silencing plots Fig S2C

load('./CleanBehaviourdata/extractedparameters/TNTparameters/TNTparameters.mat');
[sigupTNT,sigdownTNT,magnitudeTNT]=plotparameters_TNT(tntatlasloc,parameters,{'upwind','curvature','curvatureoff'},{'LHMB'},' ','region')



%% Make imaging plots Fig 2E

makeimagingplots(pwd,'lh1396all.mat',0,0,'');
makeimagingplots(pwd,'MB052Bfullnew.mat',0,0,'');
%change the window that is being used between these for plotting
makeimagingplots(pwd,'reanalyze.mat',0,0,'');
makeimagingplots(pwd,'MB077Breanalyze.mat',0,0,'');


%% Calculate directional indices Fig 2F

%directionalratio from current data - first calculate and then plot 


%% Make anenometer plot Fig S2D 

ManifoldStimulusScript

%% example imaging plots (Fig S2E)

%make lh1396 single example 
 
alltrialstimecourse(pwd,'lh1396_012220_f1e2',2,0,1,0);

%MB052B single example 
alltrialstimecourse(pwd,'MB052B_apr2621_f1e1',2,0,1,0); % I think 

%MB077B single example
alltrialstimecourse_newthor(pwd,'MB077B_jul2021_f4e5',2,0,1,0);

%MB082C single example
alltrialstimecourse_newthor(pwd,'MB082C_jul0721_f1e3',2,0,1,0);



%% Make Fig 2G) Ephys data

load('ephysdataMBON.mat');
MBONplotting(physdata,filtdata,0);
%need to save the data from this somewhere/how
%reduce this to just plotting and doing the stats of this function